services:
  djdesweb:
    restart: unless-stopped
    build: ./djdesweb
    command: gunicorn djdesweb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./djdesweb:/usr/src/app
    ports:
      - ${PRODUCTION_DOCKER_DJANGO_API_FORWARDED_PORT}:8000
    env_file:
      - .env
      - .env.prod
    networks:
      - postgis_postgis

networks:
   postgis_postgis:
      driver: bridge
      external: true
